#Criado por Magno Reis. Não modifique este arquivo

# SIte Options
title: 1MNEWS
slogan: Seu mundo, só que na internet.
email: editor.1mn@gmail.com
url: "https://1mn.github.io"
repo: "https://github.com/alipseight/1mnews"
baseurl: #ignore

# Version Control

current_version: v0.1.0-zeppelin.1/gh-pages+build.d82966f
last_version: v0.1.0-rc.rls+build.559d8dc
version_log: Adicionado blog, 404, navbar, modificações d82966f entre outros.

# Site config
includes: [_includes]
#exclude:  .gitignore
markdown: kramdown
