#Criado por Magno Reis. Não modifique este arquivo

# SIte Options
title: 1MNEWS
slogan: Seu mundo, só que na internet.
email: editor.1mn@gmail.com
url: "https://1mn.github.io"
repo: "https://github.com/alipseight/1mnews"
baseurl: #ignore

# Version Control

current_version: v0.1.0-rc.rls+build.559d8dc
last_version: v.0.1.0-rls+build.22f19d9
version_log: Adicionado bootstrap

# Site config
includes: [_includes]
#exclude:  .gitignore
markdown: kramdown
