
# SIte Options

title: 1MN
slogan: Seu mundo, sรณ que na internet.
email: editor.1mn@gmail.com

# Site Config

current_version: 0.1.0-rls.1+build.b7fdeec
markdown: kramdown
url: "https://1mn.github.io"
repo: "https://github.com/alipseight/1mn"
